### ISSUE TITLE
error using winston-log2gelf under sails

### ISSUE THREAD

**Issue by garjonat** [Buzut/winston-log2gelf#1]
Running this under sails.js,  an error occours at this line:

**var winstongelf = require('winston-log2gelf');**

``` [javascript]
`include-all` attempted to `require(/source/adsgdwebservice/config/log.js)`, but an error occurred::
Details:SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by Buzut** [comment]
I added a `'use strict';` that should solve your problem. Tell me if it works.
PS: anyway, `require(/source/adsgdwebservice/config/log.js)` isn't my module…

**Comment by garjonat** [comment]
Thank you very much. it works.
