### ISSUE TITLE
Silence Logger

### ISSUE THREAD

**Issue by sirishamalarapu** [Buzut/winston-log2gelf#11]
I see logger sending data over tcp even after we set silence to true. After looking the code I don't see this.silent being used anywhere.

this.send(JSON.stringify(gelfMsg)); I guess this should be done only if silent is false.

Please comment.

**Comment by Buzut** [comment]
You're right! I'd even return early before processing the log. The only thing I'm not sure of is the usefullness of both `this.emit('logged', info);` and the `callback` calls. Do we need to call them when `silent` is `true` for instance?
I openned [an issue](https://github.com/winstonjs/winston/issues/1393) asking this exact question. 

I'll fix the problem once I know a bit more about the necessity of these things.

**Comment by sirishamalarapu** [comment]
I believe both 'logged' event and callback can be used when we are writing tests. As i am still a beginner with nodejs, i am not very sure though.

in case of silent, callback() can be called without doing anything else. this.emit('logged') can be fired only after needed logging is done; that is only when silent is false.

**Comment by Buzut** [comment]
I completely removed logged since I don't see what it's for. But without `callback`, subsequent calls to logger aren't logged. 
Issue should be fixed now.
