### ISSUE TITLE
Graylog connection problems shuts down express

### ISSUE THREAD

**Issue by mihaiblaga89** [Buzut/winston-log2gelf#3]
Firstly, I would like the app not to crash if it can't connect to the graylog server in the first place.
Second, the app "exits"([nodemon] clean exit - waiting for changes before restart) if it looses connection with the graylog server.

**Comment by Buzut** [comment]
I'm sorry I hadn't had time to give your issue a look. I've seen that you've forked, removing the `process.exit`. Seems ok to me, as Express should continue to run even if the logger can't connect. 

I'd accept the PR if you submit.

**Comment by mihaiblaga89** [comment]
Sure. Another thing that it's more annoying than mission critical is that if the graylog server is down, or something like that, somehow the send function is called multiple times. I'm guessing it's a listener applied multiple times issue? Or is it a winston issue? For example, I start the server and at the first message that it tries to send to graylog I get the error "can't connect to graylog". All good here. At the second message it tries to send, I get 2 x "can't connect to graylog", and so on

**Comment by Buzut** [comment]
Thanks for spotting this out. It was actually a redundant error listener declared in the tcp send function. So it was bound each time send was called. Fixed in 1.3.1

**Comment by mihaiblaga89** [comment]
Thank you. I am working as we speak at a reconnect feature. I'll make a pull request when ready

**Comment by Buzut** [comment]
Super nice, thank you!
