### ISSUE TITLE
Static fields in winston-log2gelf

### ISSUE THREAD

**Issue by ghost** [Buzut/winston-log2gelf#6]
Hi, in other GELF logging libraries such as pygelf (for python) and gelfclient (for Java) it's possible to send "custom" static fields to graylog by defining them with an underscore (_) in the declaration of the logger.  

**For example**, with pygelf, I'm declaring a "foo" key with a value of "bar": 

`GelfTcpHandler(host='graylog.example.com', port=12201, chunk_size=1350, _environment="prod", _foo="bar"))`

Then, in graylog, there is literally a new field that shows up "foo" for that message. 

I've tried doing this in the same format with winston-log2gelf, but I'm not sure if it works and/or possible. 

If it is not a capability, please treat this as a feature request.

**Comment by Buzut** [comment]
Hi,

Indeed, it's currently not supported. I'll give this a look in the coming days.

**Comment by Buzut** [comment]
I added the functionality

**Comment by ghost** [comment]
Thank you, this will be helpful in our projects.
