### ISSUE TITLE
Typo that breaks the whole thing

### ISSUE THREAD

**Issue by sfertman** [Buzut/winston-log2gelf#7]
https://github.com/Buzut/winston-log2gelf/blob/master/lib/index.js#L152

**Comment by Buzut** [comment]
Hi,
What version of node do you use? 
This is in fact not a typo but ES6 object spread operator. This might not work in all node versions though. In that case, I'd revert the change and bump this function to a major version specifying min node version. 

Or you can PR with a node < 8 compatible version, replacing object spread with compatible code (`Object.assign` should do for instance).

**Comment by hereandnow** [comment]
critical issue for us too. 

i think the best thing to do is revert the changes, add engines < 8 to the package.json, add your changes again, add engines >=8 to the package.json and do a major version bump

**Comment by Buzut** [comment]
Used `Object.assign` instead of object spread

**Comment by sfertman** [comment]
@Buzut Thanks!
