### ISSUE TITLE
Getting `this socket is closed`.

### ISSUE THREAD

**Issue by FrankPetrilli** [Buzut/winston-log2gelf#8]
Seeing `Error connecting to Graylog: This socket is closed` from log2gelf, looks like it's coming from https://github.com/Buzut/winston-log2gelf/blob/master/lib/index.js#L51. Would you be willing to accept a PR including a reconnect on fail function?

**Comment by Buzut** [comment]
Hey. 

I was abroad these last days, sorry for my late answer. Sure, I'd be glad to accept a PR.

**Comment by doitlikepruett** [comment]
Hi there, I'm seeing this issue as well. Tried upgrading to 2.0.3 and yet it persists. Before this however, I see `Error connecting to Graylog: This socket has been ended by the other party`. Any assitance is appreciated!

**Comment by Buzut** [comment]
Hi @doitlikepruett 
The error is triggered at [line 87](https://github.com/Buzut/winston-log2gelf/blob/master/index.js#L87).
So is this immediate or does it happen after some time? What about `reconnect`'s value?

**Comment by doitlikepruett** [comment]
Hi @Buzut, sorry I never saw your response! 

We're still seeing this from time to time. 

It happens apparently randomly.

```
Error connecting to Graylog: read ECONNRESET
Error connecting to Graylog: This socket is closed
Error connecting to Graylog: This socket is closed
Error connecting to Graylog: This socket is closed
Error connecting to Graylog: This socket is closed
...
```
Then it seems to resume connection. `reconnect` value is -1. My connection pool is `Infinity` so I don't think it's on my server's end. 

Thanks again for the tool.

**Comment by gsabatini2016** [comment]
Keep showing this error

Error connecting to Graylog: This socket is closed
Connected to Graylog server
Connected to Graylog server
Error connecting to Graylog: This socket is closed
