### ISSUE TITLE
protocol parameter unclear

### ISSUE THREAD

**Issue by geert-b** [Buzut/winston-log2gelf#9]
According to the explenation in the README I used uppercase parameters for the protocol option. This failed with an unclear error.
I would suggest one of the following:
- update the README to state that the param needs to be lowercase
- throw an error stating that the supplied param doesn't match a known protocol (and maybe print the different options)
- do a toLowerCase() on the variable in the code

Apart from that minor issue: thanks for the plugin! ;)

edit: I see now that the README on github has lowercase options in the explenation but it is still in uppercase on npmjs.com...

**Comment by Buzut** [comment]
Hello,
Thank you for your interest. Actually, the doc had been updated on github but not on npm, my bad.
So I modified the code to raise an error if the protocol isn't valid and also updated doc on npm.
